# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rephraser.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0frephraser.proto\x12\trephraser\"[\n\x0fRephraseRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x13\n\x0btemperature\x18\x02 \x01(\x02\x12\x0e\n\x06sample\x18\x03 \x01(\x08\x12\x15\n\rnum_sequences\x18\x04 \x01(\x05\"7\n\rRephraseReply\x12&\n\tsequences\x18\x01 \x03(\x0b\x32\x13.rephraser.Sequence\"\'\n\x08Sequence\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x02\x32O\n\tRephraser\x12\x42\n\x08Rephrase\x12\x1a.rephraser.RephraseRequest\x1a\x18.rephraser.RephraseReply\"\x00\x62\x06proto3')



_REPHRASEREQUEST = DESCRIPTOR.message_types_by_name['RephraseRequest']
_REPHRASEREPLY = DESCRIPTOR.message_types_by_name['RephraseReply']
_SEQUENCE = DESCRIPTOR.message_types_by_name['Sequence']
RephraseRequest = _reflection.GeneratedProtocolMessageType('RephraseRequest', (_message.Message,), {
  'DESCRIPTOR' : _REPHRASEREQUEST,
  '__module__' : 'rephraser_pb2'
  # @@protoc_insertion_point(class_scope:rephraser.RephraseRequest)
  })
_sym_db.RegisterMessage(RephraseRequest)

RephraseReply = _reflection.GeneratedProtocolMessageType('RephraseReply', (_message.Message,), {
  'DESCRIPTOR' : _REPHRASEREPLY,
  '__module__' : 'rephraser_pb2'
  # @@protoc_insertion_point(class_scope:rephraser.RephraseReply)
  })
_sym_db.RegisterMessage(RephraseReply)

Sequence = _reflection.GeneratedProtocolMessageType('Sequence', (_message.Message,), {
  'DESCRIPTOR' : _SEQUENCE,
  '__module__' : 'rephraser_pb2'
  # @@protoc_insertion_point(class_scope:rephraser.Sequence)
  })
_sym_db.RegisterMessage(Sequence)

_REPHRASER = DESCRIPTOR.services_by_name['Rephraser']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REPHRASEREQUEST._serialized_start=30
  _REPHRASEREQUEST._serialized_end=121
  _REPHRASEREPLY._serialized_start=123
  _REPHRASEREPLY._serialized_end=178
  _SEQUENCE._serialized_start=180
  _SEQUENCE._serialized_end=219
  _REPHRASER._serialized_start=221
  _REPHRASER._serialized_end=300
# @@protoc_insertion_point(module_scope)
